# Generated by Django 4.0.3 on 2022-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('code', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('aulas_semanais', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=5)),
                ('enquadramento', models.IntegerField(choices=[(1, 'Presencial'), (2, 'Hibrida'), (3, 'Remoto')], default=1)),
                ('vagas_total', models.IntegerField(default=0)),
                ('vagas_calouros', models.IntegerField(default=0)),
                ('reserva', models.CharField(max_length=20)),
                ('prioridade_curso', models.CharField(max_length=150)),
                ('horario', models.CharField(max_length=150)),
                ('professor', models.CharField(max_length=120)),
                ('optativa', models.CharField(max_length=400)),
            ],
        ),
    ]
