# Generated by Django 4.0.3 on 2022-03-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalible_classes', '0002_disciplina_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='codigo',
            new_name='codigo_disciplina',
        ),
        migrations.RenameField(
            model_name='turma',
            old_name='turma',
            new_name='codigo_turma',
        ),
        migrations.AddField(
            model_name='turma',
            name='codigo_disciplina',
            field=models.CharField(default='', max_length=15),
        ),
    ]
